namespace images {
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsBigSmile = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsHeartLarge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsHeartSmall = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsMouth1open = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsMouth1shut = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsMouth2open = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsMouth2shut = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsSad = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsSick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsSmile = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsSwearing = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsTalking = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsWink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const expressionsZzz = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesAngry = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesAwake = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesBlackEye = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesBottomLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesBottomRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesCrazy1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesCrazy2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesDisappointed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesDizzy = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesEvil = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesHurt = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesKnockedOut = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesLove = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesMiddleLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesMiddleRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesNeutral = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesNuclear = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesPinchLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesPinchMiddle = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesPinchRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesSleeping = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesTear = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesTiredLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesTiredMiddle = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesTiredRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesToxic = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const eyesWinking = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationAccept = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationBackward = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationDecline = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationForward = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationNoGo = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationQuestionMark = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationStop1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationStop2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationThumbsDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationThumbsUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const informationWarning = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoColorSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoEv3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoEv3icon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoGyroSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoIrBeacon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoIrSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoLargeMotor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoLego = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoMediumMotor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoMindstorms = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoSoundSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoTempSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoTouchSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const legoUsSensor = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsBomb = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsBoom = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsFire = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsFlowers = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsForest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsLightning = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsLightOff = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsLightOn = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsNight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsPirate = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsSnow = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const objectsTarget = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressBar0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressBar1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressBar2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressBar3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressBar4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDial0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDial1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDial2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDial3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDial4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDots0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDots1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDots2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressDots3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressHourglass0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressHourglass1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressHourglass2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressTimer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressTimer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressTimer2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressTimer3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressTimer4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressWaterLevel0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressWaterLevel1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressWaterLevel2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const progressWaterLevel3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const systemAccept1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const systemAccept2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const systemBox = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const systemDecline1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=brick.__imagePicker
    export const systemDecline2 = image.ofBuffer(hex``);
}
